name: 12
timestamp: 1663423798
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1648304591
positions:
  slideshow-a: 'Slideshow A'
  header-a: 'Header A'
  above-a: 'Above A'
  feature-a: 'Feature A'
  showcase-a: 'Showcase A'
  utility-a: 'Utility A'
  sidebar-a: 'Sidebar A'
  mainbar-a: 'MainBar A'
  aside-a: 'Aside A'
  expanded-a: 'Expanded A'
  extension-a: 'Extension A'
  bottom-a: 'Bottom A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-6661: 'Slideshow A'
    position-position-7051: 'Header A'
    position-position-3264: 'Above A'
    position-position-7980: 'Feature A'
    position-position-9435: 'Showcase A'
    position-position-5239: 'Utility A'
    position-position-9414: 'Sidebar A'
    position-position-8547: 'MainBar A'
    position-position-8807: 'Aside A'
    position-position-8124: 'Expanded A'
    position-position-4800: 'Extension A'
    position-position-3343: 'Bottom A'
  content:
    system-content-1120: 'Page Content'
  messages:
    system-messages-3704: 'System Messages'
  logo:
    logo-3658: 'Logo / Image'
  menu:
    menu-1142: Menu
  custom:
    custom-1164: 'Custom HTML'
  copyright:
    copyright-8216: Copyright
  mobile-menu:
    mobile-menu-4573: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-3704: system-messages-9828
    logo-3658: logo-3453
    menu-1142: menu-2872
    custom-1164: custom-9551
    copyright-8216: copyright-6444
    mobile-menu-4573: mobile-menu-2576
