name: 13
timestamp: 1648340804
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1648304591
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  promo:
    promo-6483: Promo
  slider:
    slider-8051: Slider
  logos:
    logos-1631: Logos
  infolist:
    infolist-7988: 'Info List'
  showcase:
    showcase-4509: Showcase
  iconpromo:
    iconpromo-7044: 'Icon Promo'
  testimonials:
    testimonials-7527: Testimonials
  pricingtable:
    pricingtable-1875: 'Pricing Table'
  comparisontable:
    comparisontable-2623: 'Comparison Table'
  video:
    video-8023: Video
  simplecontent:
    simplecontent-6925: 'Simple Content'
    simplecontent-9182: 'Simple Content'
  button:
    button-9920: Button
    button-5829: Button
  stories:
    stories-4803: 'User Stories'
  gridstatistic:
    gridstatistic-9706: 'Grid Statistic'
  mobile-menu:
    mobile-menu-2576: 'Mobile Menu'
  messages:
    system-messages-2686: 'System Messages'
  logo:
    logo-4286: 'Logo / Image'
  menu:
    menu-4627: Menu
  social:
    social-3097: Social
  simplemenu:
    simplemenu-6521: 'Simple Menu'
  newsletter:
    newsletter-8674: Newsletter
  copyright:
    copyright-6729: Copyright
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    system-messages-2686: system-messages-9828
    logo-4286: logo-3453
    menu-4627: menu-2872
    social-3097: social-7974
    simplecontent-9182: simplecontent-4419
    simplemenu-6521: simplemenu-2324
    newsletter-8674: newsletter-5881
    copyright-6729: copyright-6444
