name: 13
timestamp: 1664323060
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1648304591
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  module:
    position-module-7216: 'Module Instance'
  promo:
    promo-6483: Promo
  custom:
    custom-4283: 'Custom HTML'
    custom-1448: 'Custom HTML'
    custom-9888: 'Custom HTML'
    custom-6768: 'Custom HTML'
  messages:
    system-messages-2686: 'System Messages'
  logo:
    logo-1982: 'Logo / Image'
  menu:
    menu-7214: Menu
  copyright:
    copyright-6729: Copyright
  mobile-menu:
    mobile-menu-8164: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-2686: system-messages-9828
    logo-1982: logo-3453
    menu-7214: menu-2872
    custom-6768: custom-9551
    copyright-6729: copyright-6444
    mobile-menu-8164: mobile-menu-2576
