name: '13'
timestamp: 1652537440
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1648304591
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-2686: 'System Messages'
  logo:
    logo-4286: 'Logo / Image'
  menu:
    menu-4627: Menu
  social:
    social-3097: Social
  module:
    position-module-7216: 'Module Instance'
  promo:
    promo-6483: Promo
  custom:
    custom-4283: 'Custom HTML'
    custom-1448: 'Custom HTML'
    custom-9888: 'Custom HTML'
    custom-6768: 'Custom HTML'
  copyright:
    copyright-6729: Copyright
  mobile-menu:
    mobile-menu-2576: 'Mobile Menu'
inherit:
  default:
    top: top
    system-messages-2686: system-messages-9828
    navigation: navigation
    logo-4286: logo-3453
    menu-4627: menu-2872
    social-3097: social-7974
    footer: footer
    custom-6768: custom-9551
    copyright: copyright
    copyright-6729: copyright-6444
