version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1648304591
layout:
  /container-top/:
    -
      -
        top: {  }
    -
      -
        navigation: {  }
    -
      -
        /slideshow/:
          -
            - position-module-7216
          -
            - promo-6483
  /header/:
    -
      - custom-4283
    -
      - custom-1448
  /above/: {  }
  /feature/: {  }
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60': {  }
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/: {  }
  /bottom/:
    -
      - custom-9888
  /container-footer/:
    -
      -
        footer: {  }
        copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
        - block
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: 'fp-slideshow no-background-image'
      variations: ''
  container-top:
    attributes:
      boxed: ''
      class: no-background-image
      extra: {  }
  header:
    attributes:
      boxed: ''
      class: fp-header
      variations: section-horizontal-paddings
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  footer:
    inherit:
      outline: default
      include:
        - block
        - children
        - attributes
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  position-module-7216:
    title: 'Module Instance'
    attributes:
      module_id: '112'
      key: module-instance
  promo-6483:
    attributes:
      enabled: 0
      headline: 'Available Today'
      title: 'Make an Incredible Product Website'
      text: 'Orion is a fast, friendly design for any project.'
  custom-4283:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"new-user-strip\" style=\"background: center / cover no-repeat url(/images/welcomeback.jpg);\">\n\t<div class=\"container\">\n\t\t<a href=\"/about/im-new-here\">\n\t\t\t<div class=\"newbox\">\n\t\t\t\t<h1 class=\"text-new-user\">\n\t\t\t\t\t<span class=\"text-bold-white\">NEW</span>\n\t\t\t\t\t<span class=\"text-small-light\">TO</span>\n\t\t\t\t\t<span class=\"namequestion\">\n\t\t\t\t\t\t<span class=\"church-name\"><b>Covenant</b> <br> Baptist Church</span>\n\t\t\t\t\t\t<span class=\"text-bold-white q-mark\">?</span>\n\t\t\t\t\t</span>\n\t\t\t\t</h1>\n\t\t\t</div>\n\t\t</a>\n\t\t<div class=\"times\">\n\t\t\t\t<b>Sunday Times:</b> 9:00am - Sunday School  &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp;  &nbsp; 10:15am - Worship Service &nbsp; &nbsp;\n\t\t\t\t<a href=\"/times\" class=\"schedule\">View Full Schedule</a>\n\t\t</div>\n\t\t<div class=\"hiddenwelcome \"><b>NEW?</b> Find out what to expect!</div>\n\t\t<a href=\"/about/im-new-here\">\n\t\t\t<div class=\"visitorbutton fade1\">Click to find out <b>what to expect</b></div>\n\t\t</a>\n\t</div>\n</section>\n"
    block:
      class: no-pad-vertical-g-content
  custom-1448:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"container two-columns px-0\">\n\t<div class=\"row row-centered\">\n\t\t<div class=\"col col-12 col-sm-6 mb-4 mt-sm-4 pl-4 pr-4 pr-md-4 pr-sm-2 mt-5\">\n\t\t\t<a href=\"resources/sermons/watch-live\"><img src=\"/images/watchlive.jpg\" class=\"fade1 w-100\"></a>\n\t\t</div>\n\t\t<div class=\"col col-12 col-sm-6 mb-4 mt-sm-4 pl-4 pr-4 pl-md-4 pl-sm-2\">\n\t\t\t<a href=\"https://cbclancaster.churchcenter.com/registrations\"><img src=\"/images/eventregister.jpg\" class=\"fade1 w-100\"></a>\n\t\t</div>\n\t</div>\n</div>"
  custom-9888:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"newstitle text-center text-uppercase\">\n<div>\n  <span style=\"font-size: 1.8rem;\" class=\"d-block d-sm-inline mb-2 mb-sm-auto me-0 me-sm-2\"><b style=\"color: #458EC7;\">Latest</b> News</span>\n  <button type=\"button\" class=\"btn\" onclick=\"window.location.href='/announcements';\">View All Announcements</button>\n</div>\n</div>"
